# Generated by Django 6.1.1 on 2026-10-04 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OffresApp', '0001_initial'),
        ('VehiculesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='vehicule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offres', to='VehiculesApp.vehicule'),
        ),
    ]
