# Generated by Django 6.1.1 on 2026-10-05 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntreprisesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='adresse',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(20, 'ladresse doit etre superieur a 20 charactere')]),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='matricule_fiscale',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Format invalide. format attendu : 7 chiffres, 1 lettres ( clé de controle), 1 lettre (A/B/D/N/P), 1 lettre (M/P/C/N/E), 3 chiffres(ex. 1234567AAM000 ou 1234567-A-A-M-000). Exemples : 1234567AAM000, 1234567/A/A/M/000 ou 1234567-A-A-M-000.', regex='^\\d{7}[/ -]?[A-Za-z][/ -]?[ABDNPEabdnpe][/ -]?[MPCNEmpcne][/ -]?\\d{3}$')]),
        ),
    ]
