# Generated by Django 6.1.1 on 2026-10-04 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EntreprisesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('ville_depart', models.CharField(max_length=100)),
                ('ville_arrivee', models.CharField(max_length=100)),
                ('poids_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_souhaitee', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('publie', 'Publie'), ('attribuee', 'Attribuee'), ('en_cours', 'En_Cours'), ('licree', 'Livree'), ('annulee--defaut publiee', 'Annulee--Defaut Publiee')], default='publie', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expeditions', to='EntreprisesApp.entreprise')),
            ],
        ),
    ]
